export const _TYPE_LOGEMENT_LIST = ["HABITATION", "COMMERCIAL", "ENTREPOT", "MAGASIN", "SERVICES"];
export const _TYPE_ACQUEREUR_LIST = ["PARTICULIER", "ENTREPRISE", "INDUSTRIE", "PROPRIETAIRE_TERRIEN", "SERVICE_PUBLIC"];
export const _TYPE_DOC_LIST = ["CARTE_NATIONALE", "PASSPORT_ORDINAIRE", "CARTE_SEJOUR", "AUTRES"];
export const _TYPE_GENRE_LIST = ["-", "M.", "Mme", "Mlle", "NON PRECISE"];